// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package repository

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Role struct {
	ID        uuid.UUID
	Name      string
	Level     int32
	CreatedAt pgtype.Timestamptz
}

type User struct {
	ID           uuid.UUID
	Username     string
	PasswordHash string
	FullName     string
	Email        string
	IsActive     bool
	RoleID       uuid.UUID
	CreatedAt    pgtype.Timestamptz
	Version      int32
}
